Repository qiskit-community/qiskit-algorithms, pull requests merged in 2023-08, with the labels that each got.

#35 Utilize local instance of validation.py
  qiskit_algorithms/eigensolvers/numpy_eigensolver.py
  qiskit_algorithms/minimum_eigensolvers/adapt_vqe.py
  qiskit_algorithms/minimum_eigensolvers/qaoa.py
  qiskit_algorithms/optimizers/aqgd.py
  qiskit_algorithms/optimizers/p_bfgs.py
  qiskit_algorithms/optimizers/scipy_optimizer.py
  qiskit_algorithms/utils/validation.py
  test/test_validation.py
Labels: automerge

#33 A new algorithm_globals to replace use of qiskit.utils instance
  .github/workflows/main.yml
  Makefile
  docs/Makefile
  docs/apidocs/qiskit_algorithms.utils.algorithm_globals.rst
  qiskit_algorithms/__init__.py
  qiskit_algorithms/amplitude_amplifiers/grover.py
  qiskit_algorithms/optimizers/adam_amsgrad.py
  qiskit_algorithms/optimizers/gsls.py
  qiskit_algorithms/optimizers/p_bfgs.py
  qiskit_algorithms/optimizers/qnspsa.py
  qiskit_algorithms/optimizers/spsa.py
  qiskit_algorithms/optimizers/umda.py
  qiskit_algorithms/time_evolvers/pvqd/pvqd.py
  qiskit_algorithms/utils/__init__.py
  qiskit_algorithms/utils/algorithm_globals.py
  qiskit_algorithms/utils/validate_initial_point.py
  qiskit_algorithms/variational_algorithm.py
  releasenotes/notes/algorithm_globals-9a8afe956f974c86.yaml
  test/algorithms_test_case.py
  test/eigensolvers/test_vqd.py
  test/minimum_eigensolvers/test_adapt_vqe.py
  test/minimum_eigensolvers/test_qaoa.py
  test/minimum_eigensolvers/test_sampling_vqe.py
  test/minimum_eigensolvers/test_vqe.py
  test/optimizers/test_optimizer_aqgd.py
  test/optimizers/test_optimizers.py
  test/optimizers/test_optimizers_scikitquant.py
  test/optimizers/test_spsa.py
  test/optimizers/test_umda.py
  test/time_evolvers/test_pvqd.py
  test/time_evolvers/test_trotter_qrte.py
  test/time_evolvers/variational/test_var_qite.py
  test/time_evolvers/variational/test_var_qrte.py
  test/utils/test_validate_bounds.py
  test/utils/test_validate_initial_point.py
Labels: automerge

#36 Documentation fixes and updates
  docs/apidocs/qiskit_algorithms.AlgorithmError.rst
  docs/apidocs/qiskit_algorithms.gradients.rst
  docs/apidocs/qiskit_algorithms.optimizers.rst
  docs/apidocs/qiskit_algorithms.rst
  docs/apidocs/qiskit_algorithms.state_fidelities.rst
  docs/apidocs/qiskit_algorithms.time_evolvers.trotterization.rst
  docs/apidocs/qiskit_algorithms.time_evolvers.variational.rst
  docs/index.rst
  qiskit_algorithms/__init__.py
  qiskit_algorithms/eigensolvers/__init__.py
  qiskit_algorithms/gradients/__init__.py
  qiskit_algorithms/minimum_eigensolvers/__init__.py
  qiskit_algorithms/minimum_eigensolvers/sampling_vqe.py
  qiskit_algorithms/minimum_eigensolvers/vqe.py
  qiskit_algorithms/optimizers/__init__.py
  qiskit_algorithms/state_fidelities/__init__.py
  qiskit_algorithms/time_evolvers/trotterization/__init__.py
  qiskit_algorithms/time_evolvers/variational/__init__.py
Labels: documentation, automerge

#64 Remove best measurement text - fixes #48
  qiskit_algorithms/minimum_eigensolvers/qaoa.py
  qiskit_algorithms/minimum_eigensolvers/sampling_vqe.py
Labels: documentation

#65 Fix result print for SamplingVQE & QAOA - fixes #58
  qiskit_algorithms/minimum_eigensolvers/sampling_mes.py
  releasenotes/notes/update_sampling_result-6f65d2c54d7a88c3.yaml
Labels: automerge

#66 Add tutorial `13_trotterQRTE.ipynb`
  .pylintdict
  docs/tutorials/13_trotterQRTE.ipynb
Labels: automerge

#69 Post-release update (0.2.0)
  .mergify.yml
  qiskit_algorithms/VERSION.txt
Labels: automerge

#70 Fix test suite to account for beta numpy versions
  test/optimizers/test_optimizers_scikitquant.py
Labels: automerge
