Repository qiskit-community/qiskit-algorithms, pull requests merged in 2024-02, with the labels that each got.

#142 Update intersphinx links and others
  docs/conf.py
  docs/tutorials/01_algorithms_introduction.ipynb
  docs/tutorials/02_vqe_advanced_options.ipynb
  docs/tutorials/04_vqd.ipynb
  docs/tutorials/05_qaoa.ipynb
  docs/tutorials/07_grover_examples.ipynb
  docs/tutorials/10_pvqd.ipynb
  docs/tutorials/11_VarQTE.ipynb
Labels: stable backport potential

#143 Add dependabot to manage future Github Actions updates
  .github/dependabot.yml
Labels: automerge

#141 Add slow_test as it's no longer part of Qiskit 1.0
  test/__init__.py
  test/decorators.py
  test/eigensolvers/test_vqd.py
  test/gradients/test_estimator_gradient.py
  test/minimum_eigensolvers/test_sampling_vqe.py
  test/minimum_eigensolvers/test_vqe.py
  test/optimizers/test_optimizer_aqgd.py
  test/time_evolvers/test_pvqd.py
Labels: stable backport potential

#147 Update links to Aer docs now that its on github pages
  docs/tutorials/01_algorithms_introduction.ipynb
  docs/tutorials/03_vqe_simulation_with_noise.ipynb
Labels: documentation, stable backport potential

#148 Update SPSA examples in class docstring
  qiskit_algorithms/optimizers/spsa.py
Labels: documentation, automerge, stable backport potential

#153 Fix bad release note link
  releasenotes/notes/0.1/migrate-algrithms-from-terra-6a8aa994d1206806.yaml
Labels: automerge

#156 Fix tutorials to work with Qiskit 1.0
  .pylintdict
  docs/tutorials/01_algorithms_introduction.ipynb
  docs/tutorials/02_vqe_advanced_options.ipynb
  docs/tutorials/03_vqe_simulation_with_noise.ipynb
  docs/tutorials/04_vqd.ipynb
  docs/tutorials/05_qaoa.ipynb
  docs/tutorials/06_grover.ipynb
  docs/tutorials/07_grover_examples.ipynb
  docs/tutorials/10_pvqd.ipynb
  docs/tutorials/11_VarQTE.ipynb
  docs/tutorials/12_gradients_framework.ipynb
  docs/tutorials/13_trotterQRTE.ipynb
  docs/tutorials/tutorial_magics.py
Labels: automerge

#158 Prepare 0.3.0 release
  releasenotes/notes/0.3/add-barriers-trotter-248cccabbf9deed1.yaml
  releasenotes/notes/0.3/fix-fidelity-00fbfa9919e860de.yaml
  releasenotes/notes/0.3/fix_aqgd_max_grouped_evals-fbe108c005a9b7ac.yaml
  releasenotes/notes/0.3/fix_fidelity_cache-3a4cc328344716e0.yaml
  releasenotes/notes/0.3/fix_gsls_bounds-29d4a7506130cd69.yaml
  releasenotes/notes/0.3/py_3_12_support-13aa1a32494d25e7.yaml
  releasenotes/notes/0.3/qiskit_1_0_compatible-405b357d032fbeeb.yaml
Labels: automerge

#160 Revert Python 3.12.0 specific usage
  .github/workflows/main.yml
Labels: automerge, stable backport potential
