Repository qiskit-community/qiskit-algorithms, pull requests merged in 2024-01, with the labels that each got.

#119 Pin nbconvert to < 7.14 to workaround issue
  constraints.txt
Labels: stable backport potential

#115 Deploy docs to GitHub Pages
  .github/workflows/deploy-docs.yml
  tools/deploy_documentation.sh
  tools/rclone.conf.enc
Labels: documentation, stable backport potential

#122 Update unit test as toffoli is deprecated
  test/gradients/test_estimator_gradient.py
  test/gradients/test_sampler_gradient.py
Labels: automerge

#121 Remove py.typed until #74 is addressed
  qiskit_algorithms/py.typed
Labels: automerge

#139 Update actions using deprecated Node.js
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-code.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: automerge, stable backport potential

#128 added insert_barrier to TrotterQRTE
  qiskit_algorithms/time_evolvers/trotterization/trotter_qrte.py
  releasenotes/notes/add-barriers-trotter-248cccabbf9deed1.yaml
  test/time_evolvers/test_trotter_qrte.py
Labels: automerge
